In [1]:
# !pip3 install torch

In [2]:
import torch

/home/gans/miniconda3/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# Создайте случайный FloatTensor размера 3x4x5

In [40]:
a = torch.rand(3, 4, 5)
print(a.type())
a

torch.FloatTensor


tensor([[[0.7492, 0.4141, 0.9585, 0.5218, 0.7194],
         [0.7965, 0.4283, 0.1259, 0.5208, 0.5242],
         [0.7933, 0.2636, 0.4172, 0.4343, 0.0699],
         [0.1142, 0.7220, 0.3209, 0.3634, 0.4913]],

        [[0.8301, 0.6676, 0.8017, 0.2401, 0.5760],
         [0.9106, 0.2631, 0.3419, 0.3801, 0.4892],
         [0.2369, 0.5654, 0.4751, 0.8733, 0.9345],
         [0.4440, 0.1347, 0.3912, 0.2516, 0.8198]],

        [[0.2025, 0.2194, 0.8029, 0.6862, 0.8096],
         [0.2277, 0.5338, 0.2154, 0.1497, 0.9236],
         [0.8255, 0.3186, 0.0413, 0.1597, 0.8445],
         [0.0152, 0.1458, 0.9253, 0.8691, 0.2953]]])

In [5]:
# Выведите его форму (shape)

In [41]:
a.shape

torch.Size([3, 4, 5])

In [26]:
# Приведите его к форме 6 X 10

In [43]:
b = a.reshape(6, 10)
b

tensor([[0.7492, 0.4141, 0.9585, 0.5218, 0.7194, 0.7965, 0.4283, 0.1259, 0.5208,
         0.5242],
        [0.7933, 0.2636, 0.4172, 0.4343, 0.0699, 0.1142, 0.7220, 0.3209, 0.3634,
         0.4913],
        [0.8301, 0.6676, 0.8017, 0.2401, 0.5760, 0.9106, 0.2631, 0.3419, 0.3801,
         0.4892],
        [0.2369, 0.5654, 0.4751, 0.8733, 0.9345, 0.4440, 0.1347, 0.3912, 0.2516,
         0.8198],
        [0.2025, 0.2194, 0.8029, 0.6862, 0.8096, 0.2277, 0.5338, 0.2154, 0.1497,
         0.9236],
        [0.8255, 0.3186, 0.0413, 0.1597, 0.8445, 0.0152, 0.1458, 0.9253, 0.8691,
         0.2953]])

In [35]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [44]:
c = torch.tensor([1, 4, 2, 2, 1])
c

tensor([1, 4, 2, 2, 1])

In [45]:
a.mul(c)

tensor([[[0.7492, 1.6564, 1.9169, 1.0435, 0.7194],
         [0.7965, 1.7131, 0.2518, 1.0416, 0.5242],
         [0.7933, 1.0542, 0.8344, 0.8687, 0.0699],
         [0.1142, 2.8882, 0.6419, 0.7269, 0.4913]],

        [[0.8301, 2.6705, 1.6033, 0.4802, 0.5760],
         [0.9106, 1.0525, 0.6839, 0.7603, 0.4892],
         [0.2369, 2.2617, 0.9502, 1.7467, 0.9345],
         [0.4440, 0.5389, 0.7824, 0.5032, 0.8198]],

        [[0.2025, 0.8777, 1.6058, 1.3724, 0.8096],
         [0.2277, 2.1353, 0.4308, 0.2994, 0.9236],
         [0.8255, 1.2746, 0.0826, 0.3195, 0.8445],
         [0.0152, 0.5831, 1.8507, 1.7382, 0.2953]]])

In [12]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [47]:
d = b @ b.T
d.shape

torch.Size([6, 6])

In [ ]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [51]:
x = torch.tensor([1, 0.5, 2], requires_grad=True)
y = x[0]**3 + x[1] - 75*x[2]
y.backward()
x.grad.sum()

tensor(-71.)

In [ ]:
# Создайте единичный тензор размера 5x6

In [48]:
e = torch.ones(5, 6)
e

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# Переведите его в формат numpy

In [49]:
e.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [ ]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

In [77]:
x =  torch.rand(3, 4, 5)
w1 = torch.rand(1, requires_grad=True)
# x, w1

y = x**w1 - 2 * x**2 + 5 
sigma = torch.nn.functional.sigmoid(y)
mse = torch.nn.functional.mse_loss(sigma, x)
x, w1, mse

(tensor([[[0.9057, 0.4030, 0.6950, 0.8670, 0.3415],
          [0.3097, 0.3169, 0.3986, 0.1951, 0.6232],
          [0.3826, 0.0944, 0.8744, 0.3367, 0.3703],
          [0.7883, 0.5541, 0.3152, 0.1740, 0.3448]],
 
         [[0.5030, 0.3742, 0.7176, 0.9408, 0.9597],
          [0.6441, 0.7023, 0.2849, 0.8618, 0.5373],
          [0.4974, 0.0677, 0.4997, 0.6532, 0.0342],
          [0.4518, 0.3701, 0.8670, 0.0365, 0.7831]],
 
         [[0.2819, 0.2743, 0.5498, 0.6497, 0.7740],
          [0.2113, 0.8324, 0.0511, 0.6798, 0.3320],
          [0.1345, 0.2888, 0.9574, 0.8739, 0.6510],
          [0.0697, 0.1653, 0.8241, 0.0224, 0.1816]]]),
 tensor([0.9367], requires_grad=True),
 tensor(0.3401, grad_fn=<MseLossBackward0>))

In [78]:
y = x**w1 - 2 * x**2 + 5 
y

tensor([[[4.2707, 5.1021, 4.7451, 4.3715, 5.1323],
         [5.1417, 5.1400, 5.1047, 5.1402, 4.8654],
         [5.1138, 5.0918, 4.3526, 5.1340, 5.1201],
         [4.5574, 4.9612, 5.1404, 5.1338, 5.1311]],

        [[5.0194, 5.1182, 4.7030, 4.1743, 4.1201],
         [4.8326, 4.7318, 5.1461, 4.3846, 4.9814],
         [5.0251, 5.0711, 5.0228, 4.8177, 5.0400],
         [5.0669, 5.1202, 4.3714, 5.0424, 4.5689]],

        [[5.1465, 5.1472, 4.9665, 4.8235, 4.5885],
         [5.1439, 4.4563, 5.0565, 4.7724, 5.1356],
         [5.1166, 5.1456, 4.1269, 4.3540, 4.8214],
         [5.0728, 5.1306, 4.4759, 5.0275, 5.1364]]], grad_fn=<AddBackward0>)

In [79]:
mse.backward()

In [80]:
w1.grad

tensor([-0.0020])